# Generated by Django 4.1.7 on 2023-02-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
